export default {
    0: {
        title: "Restarting my personal website",
        date: "2/11/2020",
        image_url: "https://upload.wikimedia.org/wikipedia/commons/1/18/React_Native_Logo.png",
        image_alt: "React logo",
        description: "I remade my personal website to share more and to set writing goals for myself",
        text: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tempus quam pellentesque nec nam aliquam sem. Lectus magna fringilla urna porttitor rhoncus. Convallis a cras semper auctor neque vitae tempus quam. Mollis aliquam ut porttitor leo a. Magna ac placerat vestibulum lectus mauris ultrices eros in. Tellus integer feugiat scelerisque varius morbi enim nunc faucibus a. Lacinia at quis risus sed vulputate odio ut enim. Pellentesque dignissim enim sit amet venenatis urna cursus eget. Tellus molestie nunc non blandit massa enim nec. Sit amet consectetur adipiscing elit. Interdum consectetur libero id faucibus nisl. Egestas maecenas pharetra convallis posuere morbi leo urna. In egestas erat imperdiet sed. Libero id faucibus nisl tincidunt eget nullam non. </p> \
        <p>Venenatis cras sed felis eget velit aliquet sagittis. Id diam maecenas ultricies mi eget mauris. Id semper risus in hendrerit gravida rutrum quisque non tellus. Quam elementum pulvinar etiam non quam lacus. Suspendisse ultrices gravida dictum fusce ut placerat orci nulla. Aliquam nulla facilisi cras fermentum odio eu feugiat pretium. Et odio pellentesque diam volutpat commodo sed egestas egestas. Mi in nulla posuere sollicitudin aliquam ultrices. Duis ultricies lacus sed turpis tincidunt id aliquet. Posuere sollicitudin aliquam ultrices sagittis. Auctor neque vitae tempus quam pellentesque nec nam. Ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Parturient montes nascetur ridiculus mus mauris vitae ultricies leo integer. Metus dictum at tempor commodo ullamcorper a lacus vestibulum. Dignissim suspendisse in est ante.</p>\
        <p>Scelerisque fermentum dui faucibus in ornare. Curabitur vitae nunc sed velit. Duis at tellus at urna condimentum. Fames ac turpis egestas maecenas pharetra. Felis bibendum ut tristique et egestas. Nullam vehicula ipsum a arcu cursus vitae. Aliquam etiam erat velit scelerisque in dictum non consectetur a. Purus non enim praesent elementum facilisis leo. Tristique senectus et netus et malesuada fames. Gravida rutrum quisque non tellus orci ac auctor. Metus vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Urna condimentum mattis pellentesque id nibh tortor id aliquet.</p>"
    },
}