export default {
    0: {
        title: "Bridging Digital and Physical Activity",
        date: "March 4, 2020",
        image_url: "https://1m9qrs2s997uox6846iotvmx-wpengine.netdna-ssl.com/wp-content/uploads/2019/02/1-Copy.png",
        credit: "https://news.nike.com/news/nike-app-at-retail-shopping-experience",
        image_alt: "Nike App",
        description: "Shopping online and offline are distinct and separate activities today. That seems to be changing slowly as your mobile phone becomes a useful aid when you are in the store.",
        text: "<p>Last summer, when I met up with some friends in a sushi restaurant in Hong Kong, I sat confused while my friends picked up their phone and started ordering their food. As I was looking around for the menu, my friends had scanned the QR code on a receipt left by the waiter and found an online menu where they could start ordering food. I quickly realized what they had done and followed suit.</p>\
        <p>Everything else in that restaurant was more familiar. I waited for food. I ate and had to wave down a busy waiter to bring the bill. Then, I paid using a debit card, while my friends Venmo'd me their share of the bill. I forgot about this experience until I was listening to a podcast and heard about Nike's new app and retail experience.</p>\
        <p>I dug into it, and the video in <a href'https://news.nike.com/news/nike-app-at-retail-shopping-experience'>this article</a> describes many of the features. I want to highlight a couple: reserve and try on, and instant checkout.</p>\
        <p>Today, when I shop for clothes at most stores, I walk around the store, looking at mannequins and shelves until I find something I like. Then, I find a store clerk, wait until he or she is done helping another customer, and then ask where I can find the shirt on a mannequin or if a shoe in my size is available. I repeat this process a few times, each time getting embarrassed about having to bother the store clerk. My friend is a shopaholic and has already picked out what he wants online and is only here to try them on, so he has already asked a clerk and is waiting for the clerk to get back. After we decide on what to purchase, we join the long line at the counter, where I realize how short a time I can stand still, on both legs.</p>\
        <p>Nike's innovative app would help both my friend and I fight our impatience and cut down shopping time. When I see a shirt on a mannequin, I can scan the QR code attached, or if I see a shoe and can't find the right size, I can scan the barcode. Then, I can request it, and it will be delivered to a marked area or directly to the fitting room. My friend can reserve the shoes he wants to try from home and go to a locker in the store to pick it up. When we have everything we want, we can checkout in the app and leave the store. To me, this is a better experience than being helped by even the most cheerful store clerk.</p>\
        <p>Both the sushi restaurant and Nike remind me of how separated our digital and physical lives are. As I thought about this while travelling in India, I instinctively wished for an app to help me check in to my hotel, help me request a razor, and let me text the concierge about the airport bus. Mobile apps are over a decade old now, but we are only seeing the apps that bridge the virtual and physical more recently.</p>\
        <p>I daydream about walking into malls, hotels, shops, restaurants, cafes, and maybe even the DMV one day and be able to use my phone as a personal assistant. I find myself saying to my friends, \"I wish I could order food from my table in the food court\" and wishes for many other products/features that all seem technologically possible and even easy.</p>\
        <p>Which is why I am working with my friends to build a system of apps that will allow business owners (potentially of all the stores I mentioned and more) to better serve their customers. We are starting with cafes and restaurants, where we hope to replicate the service of the sushi restaurant in Hong Kong, and do one better by adding payment, requests, and discounts.</p>"
    },
}