export default {
    0: {
        title: "Never Split the Difference",
        image_url: "https://images-na.ssl-images-amazon.com/images/I/51yKczFDuQL.jpg",
        text: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tempus quam pellentesque nec nam aliquam sem. Lectus magna fringilla urna porttitor rhoncus. Convallis a cras semper auctor neque vitae tempus quam. Mollis aliquam ut porttitor leo a. Magna ac placerat vestibulum lectus mauris ultrices eros in. Tellus integer feugiat scelerisque varius morbi enim nunc faucibus a. Lacinia at quis risus sed vulputate odio ut enim. Pellentesque dignissim enim sit amet venenatis urna cursus eget. Tellus molestie nunc non blandit massa enim nec. Sit amet consectetur adipiscing elit. Interdum consectetur libero id faucibus nisl. Egestas maecenas pharetra convallis posuere morbi leo urna. In egestas erat imperdiet sed. Libero id faucibus nisl tincidunt eget nullam non. </p> \
        <p>Venenatis cras sed felis eget velit aliquet sagittis. Id diam maecenas ultricies mi eget mauris. Id semper risus in hendrerit gravida rutrum quisque non tellus. Quam elementum pulvinar etiam non quam lacus. Suspendisse ultrices gravida dictum fusce ut placerat orci nulla. Aliquam nulla facilisi cras fermentum odio eu feugiat pretium. Et odio pellentesque diam volutpat commodo sed egestas egestas. Mi in nulla posuere sollicitudin aliquam ultrices. Duis ultricies lacus sed turpis tincidunt id aliquet. Posuere sollicitudin aliquam ultrices sagittis. Auctor neque vitae tempus quam pellentesque nec nam. Ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Parturient montes nascetur ridiculus mus mauris vitae ultricies leo integer. Metus dictum at tempor commodo ullamcorper a lacus vestibulum. Dignissim suspendisse in est ante.</p>\
        <p>Scelerisque fermentum dui faucibus in ornare. Curabitur vitae nunc sed velit. Duis at tellus at urna condimentum. Fames ac turpis egestas maecenas pharetra. Felis bibendum ut tristique et egestas. Nullam vehicula ipsum a arcu cursus vitae. Aliquam etiam erat velit scelerisque in dictum non consectetur a. Purus non enim praesent elementum facilisis leo. Tristique senectus et netus et malesuada fames. Gravida rutrum quisque non tellus orci ac auctor. Metus vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Urna condimentum mattis pellentesque id nibh tortor id aliquet.</p>\
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tempus quam pellentesque nec nam aliquam sem. Lectus magna fringilla urna porttitor rhoncus. Convallis a cras semper auctor neque vitae tempus quam. Mollis aliquam ut porttitor leo a. Magna ac placerat vestibulum lectus mauris ultrices eros in. Tellus integer feugiat scelerisque varius morbi enim nunc faucibus a. Lacinia at quis risus sed vulputate odio ut enim. Pellentesque dignissim enim sit amet venenatis urna cursus eget. Tellus molestie nunc non blandit massa enim nec. Sit amet consectetur adipiscing elit. Interdum consectetur libero id faucibus nisl. Egestas maecenas pharetra convallis posuere morbi leo urna. In egestas erat imperdiet sed. Libero id faucibus nisl tincidunt eget nullam non. </p> \
        <p>Venenatis cras sed felis eget velit aliquet sagittis. Id diam maecenas ultricies mi eget mauris. Id semper risus in hendrerit gravida rutrum quisque non tellus. Quam elementum pulvinar etiam non quam lacus. Suspendisse ultrices gravida dictum fusce ut placerat orci nulla. Aliquam nulla facilisi cras fermentum odio eu feugiat pretium. Et odio pellentesque diam volutpat commodo sed egestas egestas. Mi in nulla posuere sollicitudin aliquam ultrices. Duis ultricies lacus sed turpis tincidunt id aliquet. Posuere sollicitudin aliquam ultrices sagittis. Auctor neque vitae tempus quam pellentesque nec nam. Ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Parturient montes nascetur ridiculus mus mauris vitae ultricies leo integer. Metus dictum at tempor commodo ullamcorper a lacus vestibulum. Dignissim suspendisse in est ante.</p>\
        <p>Scelerisque fermentum dui faucibus in ornare. Curabitur vitae nunc sed velit. Duis at tellus at urna condimentum. Fames ac turpis egestas maecenas pharetra. Felis bibendum ut tristique et egestas. Nullam vehicula ipsum a arcu cursus vitae. Aliquam etiam erat velit scelerisque in dictum non consectetur a. Purus non enim praesent elementum facilisis leo. Tristique senectus et netus et malesuada fames. Gravida rutrum quisque non tellus orci ac auctor. Metus vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Urna condimentum mattis pellentesque id nibh tortor id aliquet.</p>\
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tempus quam pellentesque nec nam aliquam sem. Lectus magna fringilla urna porttitor rhoncus. Convallis a cras semper auctor neque vitae tempus quam. Mollis aliquam ut porttitor leo a. Magna ac placerat vestibulum lectus mauris ultrices eros in. Tellus integer feugiat scelerisque varius morbi enim nunc faucibus a. Lacinia at quis risus sed vulputate odio ut enim. Pellentesque dignissim enim sit amet venenatis urna cursus eget. Tellus molestie nunc non blandit massa enim nec. Sit amet consectetur adipiscing elit. Interdum consectetur libero id faucibus nisl. Egestas maecenas pharetra convallis posuere morbi leo urna. In egestas erat imperdiet sed. Libero id faucibus nisl tincidunt eget nullam non. </p> \
        <p>Venenatis cras sed felis eget velit aliquet sagittis. Id diam maecenas ultricies mi eget mauris. Id semper risus in hendrerit gravida rutrum quisque non tellus. Quam elementum pulvinar etiam non quam lacus. Suspendisse ultrices gravida dictum fusce ut placerat orci nulla. Aliquam nulla facilisi cras fermentum odio eu feugiat pretium. Et odio pellentesque diam volutpat commodo sed egestas egestas. Mi in nulla posuere sollicitudin aliquam ultrices. Duis ultricies lacus sed turpis tincidunt id aliquet. Posuere sollicitudin aliquam ultrices sagittis. Auctor neque vitae tempus quam pellentesque nec nam. Ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Parturient montes nascetur ridiculus mus mauris vitae ultricies leo integer. Metus dictum at tempor commodo ullamcorper a lacus vestibulum. Dignissim suspendisse in est ante.</p>\
        <p>Scelerisque fermentum dui faucibus in ornare. Curabitur vitae nunc sed velit. Duis at tellus at urna condimentum. Fames ac turpis egestas maecenas pharetra. Felis bibendum ut tristique et egestas. Nullam vehicula ipsum a arcu cursus vitae. Aliquam etiam erat velit scelerisque in dictum non consectetur a. Purus non enim praesent elementum facilisis leo. Tristique senectus et netus et malesuada fames. Gravida rutrum quisque non tellus orci ac auctor. Metus vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Urna condimentum mattis pellentesque id nibh tortor id aliquet.</p>"
    },
    1: {
        title: "Quiet",
        image_url: "https://images-na.ssl-images-amazon.com/images/I/71SLQKwNLBL.jpg",
        text: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tempus quam pellentesque nec nam aliquam sem. Lectus magna fringilla urna porttitor rhoncus. Convallis a cras semper auctor neque vitae tempus quam. Mollis aliquam ut porttitor leo a. Magna ac placerat vestibulum lectus mauris ultrices eros in. Tellus integer feugiat scelerisque varius morbi enim nunc faucibus a. Lacinia at quis risus sed vulputate odio ut enim. Pellentesque dignissim enim sit amet venenatis urna cursus eget. Tellus molestie nunc non blandit massa enim nec. Sit amet consectetur adipiscing elit. Interdum consectetur libero id faucibus nisl. Egestas maecenas pharetra convallis posuere morbi leo urna. In egestas erat imperdiet sed. Libero id faucibus nisl tincidunt eget nullam non. </p> \
        <p>Venenatis cras sed felis eget velit aliquet sagittis. Id diam maecenas ultricies mi eget mauris. Id semper risus in hendrerit gravida rutrum quisque non tellus. Quam elementum pulvinar etiam non quam lacus. Suspendisse ultrices gravida dictum fusce ut placerat orci nulla. Aliquam nulla facilisi cras fermentum odio eu feugiat pretium. Et odio pellentesque diam volutpat commodo sed egestas egestas. Mi in nulla posuere sollicitudin aliquam ultrices. Duis ultricies lacus sed turpis tincidunt id aliquet. Posuere sollicitudin aliquam ultrices sagittis. Auctor neque vitae tempus quam pellentesque nec nam. Ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Parturient montes nascetur ridiculus mus mauris vitae ultricies leo integer. Metus dictum at tempor commodo ullamcorper a lacus vestibulum. Dignissim suspendisse in est ante.</p>\
        <p>Scelerisque fermentum dui faucibus in ornare. Curabitur vitae nunc sed velit. Duis at tellus at urna condimentum. Fames ac turpis egestas maecenas pharetra. Felis bibendum ut tristique et egestas. Nullam vehicula ipsum a arcu cursus vitae. Aliquam etiam erat velit scelerisque in dictum non consectetur a. Purus non enim praesent elementum facilisis leo. Tristique senectus et netus et malesuada fames. Gravida rutrum quisque non tellus orci ac auctor. Metus vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Urna condimentum mattis pellentesque id nibh tortor id aliquet.</p>\
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tempus quam pellentesque nec nam aliquam sem. Lectus magna fringilla urna porttitor rhoncus. Convallis a cras semper auctor neque vitae tempus quam. Mollis aliquam ut porttitor leo a. Magna ac placerat vestibulum lectus mauris ultrices eros in. Tellus integer feugiat scelerisque varius morbi enim nunc faucibus a. Lacinia at quis risus sed vulputate odio ut enim. Pellentesque dignissim enim sit amet venenatis urna cursus eget. Tellus molestie nunc non blandit massa enim nec. Sit amet consectetur adipiscing elit. Interdum consectetur libero id faucibus nisl. Egestas maecenas pharetra convallis posuere morbi leo urna. In egestas erat imperdiet sed. Libero id faucibus nisl tincidunt eget nullam non. </p> \
        <p>Venenatis cras sed felis eget velit aliquet sagittis. Id diam maecenas ultricies mi eget mauris. Id semper risus in hendrerit gravida rutrum quisque non tellus. Quam elementum pulvinar etiam non quam lacus. Suspendisse ultrices gravida dictum fusce ut placerat orci nulla. Aliquam nulla facilisi cras fermentum odio eu feugiat pretium. Et odio pellentesque diam volutpat commodo sed egestas egestas. Mi in nulla posuere sollicitudin aliquam ultrices. Duis ultricies lacus sed turpis tincidunt id aliquet. Posuere sollicitudin aliquam ultrices sagittis. Auctor neque vitae tempus quam pellentesque nec nam. Ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Parturient montes nascetur ridiculus mus mauris vitae ultricies leo integer. Metus dictum at tempor commodo ullamcorper a lacus vestibulum. Dignissim suspendisse in est ante.</p>\
        <p>Scelerisque fermentum dui faucibus in ornare. Curabitur vitae nunc sed velit. Duis at tellus at urna condimentum. Fames ac turpis egestas maecenas pharetra. Felis bibendum ut tristique et egestas. Nullam vehicula ipsum a arcu cursus vitae. Aliquam etiam erat velit scelerisque in dictum non consectetur a. Purus non enim praesent elementum facilisis leo. Tristique senectus et netus et malesuada fames. Gravida rutrum quisque non tellus orci ac auctor. Metus vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Urna condimentum mattis pellentesque id nibh tortor id aliquet.</p>"
    },
    2: {
        title: "Thinking, Fast and Slow",
        image_url: "https://images-na.ssl-images-amazon.com/images/I/41RtytNpsfL._SX332_BO1,204,203,200_.jpg",
        text: "<p>This is a fascinating book about two parts of our mind (and a little on the corresponding parts in our brain). One part processes incredibly fast, so that we can act fast when we don't need to think about what we are doing. The other part allows us to think logically and solve problems. Author Daniel Kahneman calls these parts System 1 and System 2, respectively. Unfortunately for us, System 2 is rather lazy, and if System 1 has an answer for the problem our mind is solivng, System 2 tends to accept it without checking it.</p>\
            <p>Here are some interesting takeaways about our two system mind:</p><ul>\
            <li>System 1 handles many things well, but is bad at understanding statistics.</li>\
            </ul>"
    }
}